sudo: required
# dist: trusty

group: edge

# sudo: required
# group: deprecated-2017Q2

services:
  - docker

before_install:
  - docker pull alpine:3.6

install:
  - travis_retry docker build --tag bodsch/docker-samba4 .
  - docker run --detach --name samba4 bodsch/docker-samba4

script:
  - docker ps | grep -q samba4

notifications:
  email: false

cache:
  directories:
    - $HOME/docker
