
sudo: false
#addons:
#  apt:
#    packages:
#    - ldap-utils

group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-samba4 .
  - |
    docker run \
    --detach \
    --name samba4 \
    --publish 135:135 \
    --publish 137:137/udp \
    --publish 138:138/udp \
    --publish 139:139 \
    --publish 389:389 \
    --publish 389:389/udp \
    --publish 445:445 \
    --publish 464:464 \
    --publish 636:636 \
    --publish 3268:3268/tcp \
    --publish 3269:3269/tcp \
    --env SAMBA_DC_ADMIN_PASSWD="krazb4re+H5" \
    --env KERBEROS_PASSWORD="kur-z3rSh1t" \
    --env TEST_USER=true \
    bodsch/docker-samba4

script:
  - docker ps | grep -q samba4
#  - |
#    ldapsearch \
#    -H ldaps://localhost \
#    -D "Administrator@samba.lan" \
#    -w "krazb4re+H5" \
#    -b "CN=Users,DC=samba,DC=lan" \
#    '(&(objectClass=user)(sAMAccountName=grillstarling))'

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-samba4/trigger/${DOCKER_HUB_TOKEN}/
